# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20180125_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='veiws',
            new_name='views',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='veiws',
            new_name='views',
        ),
    ]
